### ISSUE TITLE
Add new Commands

### ISSUE THREAD

**Issue by devinZygann** [DZ-CLOUD/dz-terminal#1]
Can you add more commands.

Some ideas:
- passwd (Change password)
-  gsetting (Change settings from the system)

**Comment by DonnerFranzel55** [comment]
Added new Commands:
-  ls / dir
-  > / < (bash)

**Comment by DonnerFranzel55** [comment]
added external lib imports

**Comment by DonnerFranzel55** [comment]
added setenv instead of gsetting

**Comment by DonnerFranzel55** [comment]
Password change is only available if its a OS version like in DZ OS
